### ISSUE TITLE
[Feat] add in a progress bar indicator

### ISSUE THREAD

**Issue by scp-nm** [noomerzx/vue-advance-boilerplate#1]
Hey there, thanks for putting this boilerplate together. Any chance of including something like:
https://github.com/hilongjw/vue-progressbar

**Comment by noomerzx** [comment]
The concept is to just add core module that neccessary, Then you cen add anything that optional by yourself :).

But I've take a look that those repo. it's really great !! may be I'm considering to add this one. Thx so much for your feedback and sharing.
